project:
  name: cms-blog
  type: astro

content:
  - name: blog
    label: Blog
    type: collection
    path: src/blog
    create: true
    fields:
      - name: pageName
        label: Page Name
        type: string
      - name: blogTitle
        label: Blog Title
        type: string
      - name: titleTag
        label: Title Tag
        type: string
      - name: blogDescription
        label: Blog Description
        type: string
      - name: author
        label: Author
        type: string
      - name: date
        label: Date
        type: date
      - name: tags
        label: Tags
        type: list
      - name: image
        label: Image
        type: image
      - name: imageAlt
        label: Image Alt
        type: string
      - name: body
        label: Body
        type: markdown
