name: Build and Deploy to Hostinger via FTP

on:
  push:
    branches:
      - main
    paths:
      - 'src/blog/**'
      - 'src/pages/**'
      - 'src/admin/**'
      - '_data/**'
      - '_includes/**'
      - '_layouts/**'
      - '.eleventy.js'
      - 'package.json'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build the site
        run: npm run build

      - name: Upload to Hostinger via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./public/
          server-dir: /home/u951024496/domains/lime-reindeer-940639.hostingersite.com/public_html/
