name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build site
        run: npm run build

      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: 77.37.127.218
          username: u951024496.pruebacms
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./_site/
          server-dir: /domains/lime-reindeer-940639.hostingersite.com/public_html/
